[project]
authors = ["Katy Scott <k.l.scott16@gmail.com>",
           "Nasim Bondar Sahebi <sogolsahebi@gmail.com>"]
channels = ["conda-forge"]
description = "Running READII on the I-SPY cohort for radiogenomic analysis."
name = "ispy-readii"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
readii = ">=1.14.2, <2"
med-imagetools = ">=1.5.8, <2"
